# Generated by Django 3.1.6 on 2021-02-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_auto_20210212_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='date',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
