# Generated by Django 3.1.6 on 2021-03-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0008_auto_20210307_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
