# Generated by Django 3.1.6 on 2021-03-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0011_auto_20210307_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
    ]
