# Generated by Django 3.1.6 on 2021-03-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0012_remove_userprofile_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
